### ISSUE TITLE
[BUG] After Install, DLL load failed error

### ISSUE THREAD

**Issue by jpmiller25** [da-rth/yasb#123]
## Expected Behavior
running python .\src\main.py starts yasb.

## Current Behavior
`
PS C:\Users\jmiller\yasb> python .\src\main.py
Traceback (most recent call last):
  File "C:\Users\jmiller\yasb\src\main.py", line 2, in <module>
    from PyQt6.QtWidgets import QApplication
ImportError: DLL load failed while importing QtCore: The specified procedure could not be found.
`

## Steps to Reproduce

1. scoop add bucket versions
2. scoop install versions/python310
3. cd ~\
4. git clone https://github.com/da-rth/yasb
5. cd yasb\
6. pip install -r requirements.txt
7. python .\src\main.py

## Context (Environment)
Windows 10
don't think I had python installed before
not sure if I should be doing this in a python virtual environment, install instructions didn't say anything about that so I didn't.

**Comment by Alan-Manning** [comment]
https://github.com/da-rth/yasb/issues/120#issuecomment-1867481246 reinstall of PyQt6 via pip works ("pip install PyQT6 --force").

**Comment by jpmiller25** [comment]
That did it, thank you!

**Comment by S0mbr3** [comment]
Instead of having to force a PyQt6 install via pip you just have to add the missing pyqt6-tools package in the requirements.txt file. I have a PR ready to solve that issue !
